### ISSUE TITLE
Questions on the pgwatch2 configuration database - non-docker individual component installations:

### ISSUE THREAD

**Issue by bikramma** [cybertec-postgresql/pgwatch2#249] opened 2020-02-12 17:03 UTC
Hi Kaarel and Team,

I am trying to install pgwatch2 non-docker individual installs. I have these following questions:
  Q 1 – If we want to run the pgwatch2 database on the same server as the database we want to monitor, I believe we have to run it as a separate postgresql system service on a different port (e.g 5433) than the monitored database port(e.g 5432).
  Q 2 – Can we create the pgwatch2 configuration db within the  monitored database itself?
Thanks and regards,
Bikram

**Comment by kmoppel** [comment] 2020-02-13 14:09
duplicate of #247

**Closed by kmoppel** 2020-02-13 14:09 UTC
