### ISSUE TITLE
massive errors "SendToInflux: NewPoint failed: max key length exceeded" after pulling fresh pgwatch2 

### ISSUE THREAD

**Issue by georg-h** [cybertec-postgresql/pgwatch2#29] opened 2017-10-12 13:53 UTC
Hello Kaarel,
since you proposed to update pgwatch2 at all to get your fixes for my older issues and new grafana I did this today but encountered some errors afterwards. 

When checking pgwatch2.log via web console :8080/logs/pgwatch2/200 I see now a lot of these errors below:

2017/10/12 12:52:07 12:52:07.414 ERRO SendToInflux: NewPoint failed: max key length exceeded: 71714 > 65535
2017/10/12 12:52:07 12:52:07.415 ERRO SendToInflux: NewPoint failed: max key length exceeded: 71843 > 65535
2017/10/12 12:52:07 12:52:07.416 ERRO SendToInflux: NewPoint failed: max key length exceeded: 71300 > 65535
2017/10/12 12:52:07 12:52:07.417 ERRO SendToInflux: NewPoint failed: max key length exceeded: 71724 > 65535
2017/10/12 12:52:07 12:52:07.419 ERRO SendToInflux: NewPoint failed: max key length exceeded: 71744 > 65535
2017/10/12 12:52:07 12:52:07.421 ERRO SendToInflux: NewPoint failed: max key length exceeded: 71839 > 65535
2017/10/12 12:52:07 12:52:07.421 ERRO SendToInflux: NewPoint failed: max key length exceeded: 71719 > 65535

I've tried to figure out from where they are coming but ad no success.
To make sure that my restored influx backup hasn't caused these errors I started from scratch and restored only the config of pgwatch2, pgwatch2_grafana and the influxdb metastore. Before I've dropped all docker images ( "docker rmi $(docker images -q)" )  and pulled it again.
But it didn't help.

**Comment by kmoppel** [comment] 2017-10-17 06:16
This actually seems to be a bug caused by queries longer than 65535 chars...hmm, thought it got fixed already some time ago..

**Comment by kmoppel** [comment] 2017-10-17 14:53
Fixed now in https://github.com/cybertec-postgresql/pgwatch2/commit/8c53bf1e1a598264724225f29358b5748eae0b35. New image also available.

**Closed by kmoppel** 2017-10-17 14:53 UTC
Labels: bug
